site_name: ENUCC Tutorials
theme:
  name: material
  markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
dev_addr: 0.0.0.0:8000
